import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');
const pkg = JSON.parse(readFileSync(resolve(root, 'package.json'), 'utf-8'));
writeFileSync(
  resolve(root, 'src/cli/version.ts'),
  `// Auto-generated by scripts/inject-version.mjs, do not edit
export const VERSION: string = '${pkg.version}';
`
);
